/// CRDT sync module — device-to-device synchronization via Automerge.
///
/// Purpose: When a user has both a desktop node and a mobile node (same identity),
/// they need their local SQLite projections to stay in sync without a central server.
///
/// Strategy:
/// - The source chain is the authority. Automerge syncs the *projected state* (SQLite read model).
/// - Each device maintains an Automerge document representing mutable projected state.
/// - Devices exchange Automerge sync messages over a direct libp2p connection.
/// - Conflict resolution is automatic (CRDT semantics — last-write-wins per field,
///   or set-union for collections like task queues).
///
/// This module is intentionally separate from the DAG module:
/// - DAG = immutable event log (source of truth)
/// - Sync = mutable projected state (fast read model, rebuildable from DAG)

use thiserror::Error;

#[derive(Debug, Error)]
pub enum SyncError {
    #[error("automerge error: {0}")]
    Automerge(String),
    #[error("sync peer not found: {0}")]
    PeerNotFound(String),
    #[error("incompatible protocol version: expected {expected}, got {got}")]
    VersionMismatch { expected: String, got: String },
}

/// Sync message exchanged between a user's own devices.
///
/// These are generated by Automerge's sync protocol and carried over the
/// libp2p transport. They are NOT cross-node messages (those go through the DAG).
#[derive(Debug, Clone)]
pub struct SyncMessage {
    /// DID of the sending device
    pub from_did: String,
    /// DID of the target device (must share the same root identity keypair)
    pub to_did: String,
    /// Raw Automerge sync bytes
    pub payload: Vec<u8>,
    /// Unix ms
    pub timestamp: i64,
}

/// Manages CRDT sync state for a single Automerge document.
///
/// In production this wraps `automerge::AutoCommit` + `automerge::sync::State`.
/// Keeping this as a thin wrapper lets us swap the underlying CRDT library
/// without touching the rest of the protocol codebase.
pub struct SyncEngine {
    /// DID of the local node
    pub local_did: String,
}

impl SyncEngine {
    pub fn new(local_did: String) -> Self {
        Self { local_did }
    }

    /// Generate a sync message to send to a peer device.
    ///
    /// In a full implementation this calls `automerge::sync::State::generate_sync_message`.
    pub fn generate_sync_message(&mut self, _peer_did: &str) -> Result<Option<Vec<u8>>, SyncError> {
        // TODO: wrap automerge::sync::State per peer
        // Stub returns None (nothing to sync) until wired up
        Ok(None)
    }

    /// Apply an incoming sync message from a peer device.
    ///
    /// In a full implementation this calls `automerge::AutoCommit::receive_sync_message`.
    pub fn receive_sync_message(
        &mut self,
        _peer_did: &str,
        _message: &[u8],
    ) -> Result<bool, SyncError> {
        // TODO: apply automerge sync message, return true if doc changed
        Ok(false)
    }
}

/// Sync session between two of the same user's devices.
pub struct DeviceSyncSession {
    pub local_did: String,
    pub remote_did: String,
    pub established_at: i64,
}

impl DeviceSyncSession {
    pub fn new(local_did: String, remote_did: String) -> Self {
        Self {
            local_did,
            remote_did,
            established_at: chrono::Utc::now().timestamp_millis(),
        }
    }
}
